# Generated by Django 5.0.2 on 2025-06-09 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Mazmun')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/about/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': "Haqida Bo'lim",
                'verbose_name_plural': "Haqida Bo'limlari",
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kitob nomi')),
                ('author', models.CharField(max_length=200, verbose_name='Muallif')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/books/', verbose_name='Muqova')),
                ('status', models.CharField(choices=[('want_to_read', "O'qishni istyman"), ('currently_reading', "Hozir o'qiyapman"), ('completed', "O'qib tugatdim"), ('paused', "To'xtatdim")], default='want_to_read', max_length=20, verbose_name='Holat')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1 - Juda yomon'), (2, '2 - Yomon'), (3, "3 - O'rtacha"), (4, '4 - Yaxshi'), (5, "5 - Zo'r")], null=True, verbose_name='Baho')),
                ('review', models.TextField(blank=True, verbose_name='Sharh')),
                ('key_takeaways', models.TextField(blank=True, verbose_name='Asosiy xulosalar')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sahifalar soni')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('buy_url', models.URLField(blank=True, null=True, verbose_name='Sotib olish URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Tavsiya etaman')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, verbose_name='Icon')),
                ('color', models.CharField(default='#000000', help_text='Hex rang kodi', max_length=7, verbose_name='Rang')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Hozir Kategoriyasi',
                'verbose_name_plural': 'Hozir Kategoriyalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='URL nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Loyiha Kategoriyasi',
                'verbose_name_plural': 'Loyiha Kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Vosita Kategoriyasi',
                'verbose_name_plural': 'Vosita Kategoriyalari',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Maqola', 'verbose_name_plural': 'Blog Maqolalar'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Nashr etilgan'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='Mazmun'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL nomi'),
        ),
        migrations.CreateModel(
            name='NowActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/now/', verbose_name='Rasm')),
                ('url', models.URLField(blank=True, null=True, verbose_name="Bog'lanish URL")),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('progress', models.PositiveIntegerField(default=0, help_text='0-100 orasida', verbose_name='Jarayon (%)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.nowcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Hozirgi Faoliyat',
                'verbose_name_plural': 'Hozirgi Faoliyatlar',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='URL nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/projects/', verbose_name='Rasm')),
                ('technologies', models.CharField(help_text='Vergul bilan ajrating', max_length=300, verbose_name='Texnologiyalar')),
                ('demo_url', models.URLField(blank=True, null=True, verbose_name='Demo URL')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('status', models.CharField(choices=[('planning', 'Rejalashtirish'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallangan'), ('on_hold', "To'xtatilgan")], default='completed', max_length=20, verbose_name='Holat')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy loyiha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.projectcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/tools/logos/', verbose_name='Logo')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Veb-sayt URL')),
                ('proficiency', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori'), ('expert', 'Mutaxassis')], max_length=20, verbose_name='Malaka darajasi')),
                ('years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Tajriba (yil)')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Sevimli')),
                ('is_currently_using', models.BooleanField(default=True, verbose_name='Hozir ishlataman')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.toolcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Vosita',
                'verbose_name_plural': 'Vositalar',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
    ]
