# Generated by Django 5.0.2 on 2025-06-09 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_aboutsection_book_nowcategory_projectcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'About Section', 'verbose_name_plural': 'About Sections'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='nowactivity',
            options={'ordering': ['order', '-start_date'], 'verbose_name': 'Current Activity', 'verbose_name_plural': 'Current Activities'},
        ),
        migrations.AlterModelOptions(
            name='nowcategory',
            options={'ordering': ['order'], 'verbose_name': 'Now Category', 'verbose_name_plural': 'Now Categories'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'Project Category', 'verbose_name_plural': 'Project Categories'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['category__order', 'order', 'name'], 'verbose_name': 'Tool', 'verbose_name_plural': 'Tools'},
        ),
        migrations.AlterModelOptions(
            name='toolcategory',
            options={'ordering': ['order'], 'verbose_name': 'Tool Category', 'verbose_name_plural': 'Tool Categories'},
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/about/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='buy_url',
            field=models.URLField(blank=True, null=True, verbose_name='Purchase URL'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/books/', verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='book',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Finish date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Recommended'),
        ),
        migrations.AlterField(
            model_name='book',
            name='key_takeaways',
            field=models.TextField(blank=True, verbose_name='Key takeaways'),
        ),
        migrations.AlterField(
            model_name='book',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Page count'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Terrible'), (2, '2 - Bad'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.TextField(blank=True, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='book',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('want_to_read', 'Want to Read'), ('currently_reading', 'Currently Reading'), ('completed', 'Completed'), ('paused', 'Paused')], default='want_to_read', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Book title'),
        ),
        migrations.AlterField(
            model_name='nowactivity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.nowcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='nowactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='nowactivity',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='nowactivity',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='nowactivity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/now/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='nowactivity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='nowactivity',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='nowactivity',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Progress from 0-100', verbose_name='Progress (%)'),
        ),
        migrations.AlterField(
            model_name='nowactivity',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='nowactivity',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='nowactivity',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Related URL'),
        ),
        migrations.AlterField(
            model_name='nowcategory',
            name='color',
            field=models.CharField(default='#000000', help_text='Hex color code', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='nowcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='nowcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.projectcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/projects/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='completed', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='Separate with commas', max_length=300, verbose_name='Technologies'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.toolcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='is_currently_using',
            field=models.BooleanField(default=True, verbose_name='Currently using'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favorite'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='proficiency',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20, verbose_name='Proficiency level'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='years_experience',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Years of experience'),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
