# Generated by Django 4.2 on 2025-06-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_project_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_recommended',
        ),
        migrations.RemoveField(
            model_name='book',
            name='key_takeaways',
        ),
        migrations.RemoveField(
            model_name='book',
            name='review',
        ),
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL slug'),
        ),
    ]
