# Generated by Django 4.2 on 2025-06-10 06:56

from django.db import migrations
from django.utils.text import slugify


def populate_book_slugs(apps, schema_editor):
    Book = apps.get_model('blog', 'Book')
    for book in Book.objects.all():
        if not book.slug:
            slug = slugify(book.title)
            original_slug = slug
            counter = 1
            while Book.objects.filter(slug=slug).exists():
                slug = f"{original_slug}-{counter}"
                counter += 1
            book.slug = slug
            book.save()


def reverse_populate_book_slugs(apps, schema_editor):
    Book = apps.get_model('blog', 'Book')
    Book.objects.update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_book_is_recommended_remove_book_key_takeaways_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_book_slugs, reverse_populate_book_slugs),
    ]
