# Generated by Django 4.2 on 2025-06-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20250610_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Section Title')),
                ('content', models.TextField(help_text='Use HTML for links. Each tool should be on a new line starting with bullet point.', verbose_name='Content')),
                ('last_updated', models.DateField(auto_now=True, verbose_name='Last Updated')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Tool Section',
                'verbose_name_plural': 'Tool Sections',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.DeleteModel(
            name='ToolCategory',
        ),
    ]
